# Generated by Django 2.0.7 on 2018-07-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='blog_post',
        ),
        migrations.AddField(
            model_name='book',
            name='blog_post',
            field=models.ManyToManyField(to='blog.BlogPost'),
        ),
    ]
