# Generated by Django 2.0.7 on 2018-07-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180721_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='blog_post',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
